services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommdb
      MYSQL_USER: ecomm
      MYSQL_PASSWORD: ecomm123
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    image: ecomm:1.0.0
    container_name: ecomm-app
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ecommdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ecomm
      SPRING_DATASOURCE_PASSWORD: ecomm123
      JWT_SECRET: wVCOwwGCJtLJil53gx4j9xU0J491ZaCSuGMXyYKY38cd
      MAIL_USERNAME: yuvrajplayboy178@gmail.com
      MAIL_PASSWORD: awvfpqfpuhvaoyqb
    volumes:
      - name-volume:/app

volumes:
  name-volume:
  mysql-data:
